import Octicon from "@/components/octicon";
import CodeBlock from "@/components/code-block";
import { providerIds, providers } from "@/lib/providers";

export default function Home() {
  return (
    <main>
      <section className="home-hero">
        <div className="home-hero-copy">
          <span className="eyebrow">Icon metadata infrastructure</span>

          <h1>Iconarium</h1>

          <p>
            Unified icon metadata, strongly typed helpers, browser-ready ESM,
            SVG access, and mirrored package assets across multiple icon
            ecosystems.
          </p>

          <div className="home-actions">
            <a className="ui-button ui-button-primary" href="/search">
              <Octicon name="search" size={16} />
              <span>Search icons</span>
            </a>

            <a className="ui-button" href="#providers">
              <Octicon name="package" size={16} />
              <span>Browse providers</span>
            </a>

            <a
              className="ui-button"
              href="https://github.com/Killer88967/iconarium"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Octicon name="mark-github" size={16} />
              <span>View repository</span>
            </a>
          </div>
        </div>

        <div className="quick-start">
          <div className="panel-header">
            <div className="panel-title">
              <Octicon name="code" size={16} />
              <span>Quick start</span>
            </div>

            <span className="panel-meta">Octicons</span>
          </div>

          <CodeBlock>
            {`import { getIcon } from "https://iconarium.vercel.app/packages/octicons/latest";

const mark = getIcon("mark-github", 24);

console.log(mark.fileName);`}
          </CodeBlock>
        </div>
      </section>

      <section id="providers">
        <div className="section-heading github-section-heading">
          <div>
            <span className="section-kicker">Providers</span>
            <h2>Supported icon libraries</h2>
          </div>

          <span className="provider-count">{providerIds.length} providers</span>
        </div>

        <div className="provider-grid">
          {providerIds.map((providerId) => {
            const provider = providers[providerId];

            return (
              <article className="provider-panel" key={provider.id}>
                <div className="provider-panel-header">
                  <div className="provider-panel-title">
                    <Octicon name="package" size={16} />

                    <a href={`/providers/${provider.id}`}>{provider.name}</a>
                  </div>

                  <span className="status-badge">Provider</span>
                </div>

                <div className="provider-panel-body">
                  <p>{provider.description}</p>

                  <pre className="provider-code">
                    <code>{provider.example}</code>
                  </pre>
                </div>

                <div className="provider-panel-footer">
                  <a href={`/providers/${provider.id}`}>
                    Browse
                    <Octicon name="chevron-right" size={16} />
                  </a>

                  <a href={`/packages/${provider.id}/latest`}>ESM</a>

                  <a href={`/packages/${provider.id}/latest/metadata.json`}>
                    Metadata
                  </a>

                  {provider.hasAssets && (
                    <a href={`/assets/${provider.assetsProvider}`}>Assets</a>
                  )}
                </div>
              </article>
            );
          })}
        </div>
      </section>

      <section>
        <div className="section-heading github-section-heading">
          <div>
            <span className="section-kicker">Distribution</span>
            <h2>Latest or version-pinned</h2>
          </div>
        </div>

        <div className="info-panel-grid">
          <article className="info-panel">
            <div className="panel-header">
              <div className="panel-title">
                <Octicon name="versions" size={16} />
                <span>Latest</span>
              </div>
            </div>

            <div className="panel-body">
              <code>
                https://iconarium.vercel.app/packages/font-awesome/latest
              </code>

              <p>
                Resolves to the newest provider version currently generated by
                Iconarium.
              </p>
            </div>
          </article>

          <article className="info-panel">
            <div className="panel-header">
              <div className="panel-title">
                <Octicon name="repo" size={16} />
                <span>Pinned</span>
              </div>
            </div>

            <div className="panel-body">
              <code>
                https://iconarium.vercel.app/packages/font-awesome/7.3.1
              </code>

              <p>
                Immutable version URLs are ideal when you need reproducible
                production imports.
              </p>
            </div>
          </article>
        </div>
      </section>

      <section>
        <div className="section-heading github-section-heading">
          <div>
            <span className="section-kicker">Output</span>
            <h2>Built for multiple use cases</h2>
          </div>
        </div>

        <div className="info-panel-grid">
          <article className="info-panel">
            <div className="panel-header">
              <div className="panel-title">
                <Octicon name="file-code" size={16} />
                <span>JavaScript & TypeScript</span>
              </div>
            </div>

            <div className="panel-body">
              <p>
                Browser-ready ESM modules with strongly typed icon names,
                styles, variants, sizes, and metadata.
              </p>
            </div>
          </article>

          <article className="info-panel">
            <div className="panel-header">
              <div className="panel-title">
                <Octicon name="stack" size={16} />
                <span>Metadata & assets</span>
              </div>
            </div>

            <div className="panel-body">
              <p>
                Generated JSON metadata and mirrored upstream package assets
                exposed through predictable versioned URLs.
              </p>
            </div>
          </article>
        </div>
      </section>

      <footer className="home-footer">
        <Octicon name="code-square" size={16} />

        <p>
          Generated from upstream provider metadata and distributed as ESM,
          JSON, TypeScript declarations, SVG endpoints, and package assets.
        </p>
      </footer>
    </main>
  );
}
